name = "toolbox-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "first-d1"
database_id = "2563af38-2f39-4310-8bc5-05aefd2404dc"
